--auto-generated
Using("FrameWork.Common.Class", "Class")
Using("FrameWork.Common.Delegate", "Delegate")
Using("FrameWork.Common.Enum", "Enum")
Using("FrameWork.Common.IpairsSparse", "IpairsSparse")
Using("FrameWork.Common.PartialClass", "PartialClass")
Using("FrameWork.Common.Queue", "Queue")
Using("FrameWork.Common.Stack", "Stack")
UsingNow("FrameWork.ECS.ComponentEnum", "ComponentEnum")
Using("FrameWork.ECS.World", "World")
UsingNow("FrameWork.ECS.Core.BaseComponent", "BaseComponent")
Using("FrameWork.ECS.Core.BaseRepeatExecuteSys", "BaseRepeatExecuteSys")
Using("FrameWork.ECS.Core.BaseSingleExecuteSys", "BaseSingleExecuteSys")
Using("FrameWork.ECS.Core.BaseSystem", "BaseSystem")
UsingNow("FrameWork.ECS.Core.ComponentClass", "ComponentClass")
UsingNow("FrameWork.ECS.Core.ComponentTypeCache", "ComponentTypeCache")
Using("FrameWork.ECS.Core.Entity", "Entity")
Using("FrameWork.ECS.Core.Group", "Group")
Using("FrameWork.ECS.Core.SystemClass", "SystemClass")
Using("FrameWork.ECS.Core.Match.Match", "Match")
Using("FrameWork.ECS.Core.Match.MatchEnum", "MatchEnum")
Using("FrameWork.ECS.Core.Match.Matcher", "Matcher")
UsingNow("FrameWork.ECS.Core.Pool.ComponentPool", "ComponentPool")
Using("FrameWork.ECS.Core.Pool.EntityPool", "EntityPool")
Using("FrameWork.ECS.Core.Pool.SystemPool", "SystemPool")

Using("FrameWork.ECS.Logic.MoveEnum", "MoveEnum")
UsingNow("FrameWork.ECS.Logic.Components.Move.MoveComponent", "MoveComponent")
UsingNow("FrameWork.ECS.Logic.Extension.Move.MoveExtension", "MoveExtension")
Using("FrameWork.ECS.Logic.Systems.Move.MoveSystem", "MoveSystem")
UsingNow("FrameWork.ECS.Render.Components.GameObject.LoadModelComponent", "LoadModelComponent")
UsingNow("FrameWork.ECS.Render.Components.GameObject.RootComponent", "RootComponent")
UsingNow("FrameWork.ECS.Render.Extension.GameObject.LoadModelExtension", "LoadModelExtension")
UsingNow("FrameWork.ECS.Render.Extension.GameObject.RootExtension", "RootExtension")
Using("FrameWork.ECS.Render.Systems.GameObject.LoadModelSystem", "LoadModelSystem")

